-- Travel Almaré — esquema reproducible y seguro
-- Ejecutar en Supabase SQL Editor sobre un proyecto nuevo.
create extension if not exists pgcrypto;

create type public.rol_usuario as enum ('cliente', 'admin');
create type public.estado_viaje as enum ('borrador', 'publicado', 'lleno', 'cancelado', 'completado');
create type public.estado_reservacion as enum ('pendiente', 'confirmada', 'cancelada', 'completada');
create type public.estado_pago as enum ('pendiente', 'aprobado', 'rechazado', 'cancelado', 'reembolsado');

create table public.perfiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null default '',
  apellidos text not null default '',
  telefono text,
  fecha_nacimiento date,
  sexo text check (sexo is null or sexo in ('femenino','masculino','no_binario','prefiero_no_decir')),
  rol public.rol_usuario not null default 'cliente',
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.destinos (
  id bigint generated by default as identity primary key,
  titulo text not null,
  nombre text not null,
  descripcion text not null,
  precio numeric(12,2) not null check (precio >= 0),
  descuento numeric(5,2) not null default 0 check (descuento between 0 and 100),
  etiquetas text[] not null default array['Familiar']::text[],
  edad_minima integer not null default 0 check (edad_minima between 0 and 99),
  permite_ninos boolean not null default true,
  imagen_principal text,
  imagenes text[] not null default '{}',
  es_nacional boolean not null default true,
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.viajes (
  id uuid primary key default gen_random_uuid(),
  destino_id bigint not null references public.destinos(id) on delete restrict,
  origen text not null default 'Acapulco, Guerrero',
  punto_salida text not null,
  punto_llegada text not null,
  salida timestamptz not null,
  regreso timestamptz,
  duracion_minutos integer check (duracion_minutos > 0),
  capacidad integer not null check (capacidad > 0),
  precio numeric(12,2) not null check (precio >= 0),
  estado public.estado_viaje not null default 'borrador',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  check (regreso is null or regreso > salida)
);

create table public.reservaciones (
  id uuid primary key default gen_random_uuid(),
  folio text not null unique default ('ALM-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 10))),
  usuario_id uuid not null references auth.users(id) on delete restrict,
  viaje_id uuid references public.viajes(id) on delete restrict,
  destino_id bigint references public.destinos(id) on delete restrict,
  titulo_destino text not null,
  nombre_cliente text not null,
  email_cliente text not null,
  telefono text not null,
  fecha_viaje date not null,
  pasajeros integer not null check (pasajeros between 1 and 20),
  precio_unitario numeric(12,2) not null check (precio_unitario >= 0),
  total_pagar numeric(12,2) not null check (total_pagar >= 0),
  estado public.estado_reservacion not null default 'pendiente',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  check (fecha_viaje >= creado_en::date)
);

create table public.pasajeros (
  id uuid primary key default gen_random_uuid(),
  reservacion_id uuid not null references public.reservaciones(id) on delete cascade,
  nombre_completo text not null,
  creado_en timestamptz not null default now()
);

create table public.pagos (
  id uuid primary key default gen_random_uuid(),
  reservacion_id uuid not null references public.reservaciones(id) on delete restrict,
  proveedor text,
  referencia text unique,
  monto numeric(12,2) not null check (monto >= 0),
  moneda char(3) not null default 'MXN',
  estado public.estado_pago not null default 'pendiente',
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.banners (
  id uuid primary key default gen_random_uuid(),
  imagen_url text not null,
  activo boolean not null default true,
  orden integer not null default 0,
  creado_en timestamptz not null default now()
);

create table public.configuracion (
  clave text primary key,
  valor jsonb not null,
  actualizado_en timestamptz not null default now()
);

create table public.solicitudes_contacto (
  id uuid primary key default gen_random_uuid(),
  nombre text not null check (char_length(trim(nombre)) between 2 and 100),
  telefono text not null check (char_length(trim(telefono)) between 8 and 30),
  estado text not null default 'nueva' check (estado in ('nueva','contactada')),
  creado_en timestamptz not null default now()
);

create index viajes_destino_salida_idx on public.viajes(destino_id, salida);
create index reservaciones_usuario_idx on public.reservaciones(usuario_id, creado_en desc);
create index reservaciones_viaje_idx on public.reservaciones(viaje_id, estado);
create index pagos_reservacion_idx on public.pagos(reservacion_id);

create or replace function public.es_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from perfiles where id = auth.uid() and rol = 'admin' and activo); $$;

create or replace function public.crear_perfil_usuario()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  insert into perfiles(id, nombre, apellidos, telefono, fecha_nacimiento, sexo, rol)
  values(new.id, coalesce(new.raw_user_meta_data->>'nombre',''), coalesce(new.raw_user_meta_data->>'apellidos',''), new.raw_user_meta_data->>'telefono', nullif(new.raw_user_meta_data->>'fecha_nacimiento','')::date, nullif(new.raw_user_meta_data->>'sexo',''), 'cliente');
  return new;
end $$;
create trigger auth_usuario_creado after insert on auth.users for each row execute function public.crear_perfil_usuario();

create or replace function public.actualizar_marca_tiempo()
returns trigger language plpgsql as $$ begin new.actualizado_en = now(); return new; end $$;
create trigger perfiles_actualizados before update on perfiles for each row execute function actualizar_marca_tiempo();
create trigger destinos_actualizados before update on destinos for each row execute function actualizar_marca_tiempo();
create trigger viajes_actualizados before update on viajes for each row execute function actualizar_marca_tiempo();
create trigger reservaciones_actualizadas before update on reservaciones for each row execute function actualizar_marca_tiempo();
create trigger pagos_actualizados before update on pagos for each row execute function actualizar_marca_tiempo();

create or replace function public.crear_reservacion(p_viaje uuid, p_nombre text, p_telefono text, p_pasajeros integer)
returns public.reservaciones language plpgsql security definer set search_path = public as $$
declare v_viaje viajes; v_destino destinos; v_ocupados integer; v_reserva reservaciones;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_pasajeros < 1 or p_pasajeros > 20 then raise exception 'PASAJEROS_INVALIDOS'; end if;
  select * into v_viaje from viajes where id = p_viaje for update;
  if not found or v_viaje.estado <> 'publicado' or v_viaje.salida <= now() then raise exception 'VIAJE_NO_DISPONIBLE'; end if;
  select coalesce(sum(pasajeros),0) into v_ocupados from reservaciones where viaje_id=p_viaje and estado in ('pendiente','confirmada');
  if v_ocupados + p_pasajeros > v_viaje.capacidad then raise exception 'SIN_LUGARES'; end if;
  select * into v_destino from destinos where id=v_viaje.destino_id and activo;
  insert into reservaciones(usuario_id, viaje_id, destino_id, titulo_destino, nombre_cliente, email_cliente, telefono, fecha_viaje, pasajeros, precio_unitario, total_pagar)
  select auth.uid(), v_viaje.id, v_destino.id, v_destino.titulo, trim(p_nombre), u.email, trim(p_telefono), v_viaje.salida::date, p_pasajeros, v_viaje.precio, v_viaje.precio*p_pasajeros from auth.users u where u.id=auth.uid()
  returning * into v_reserva;
  return v_reserva;
end $$;

alter table perfiles enable row level security; alter table destinos enable row level security;
alter table viajes enable row level security; alter table reservaciones enable row level security;
alter table pasajeros enable row level security; alter table pagos enable row level security;
alter table banners enable row level security; alter table configuracion enable row level security;
alter table solicitudes_contacto enable row level security;

create policy "destinos públicos activos" on destinos for select using (activo or es_admin());
create policy "viajes públicos" on viajes for select using ((estado in ('publicado','lleno')) or es_admin());
create policy "banners públicos" on banners for select using (activo or es_admin());
create policy "perfil propio" on perfiles for select using (id=auth.uid() or es_admin());
create policy "actualizar perfil propio" on perfiles for update using (id=auth.uid()) with check (id=auth.uid());
create policy "reservas propias" on reservaciones for select using (usuario_id=auth.uid() or es_admin());
create policy "cliente cancela reserva propia" on reservaciones for update to authenticated using (not es_admin() and usuario_id=auth.uid() and estado in ('pendiente','confirmada')) with check (not es_admin() and usuario_id=auth.uid() and estado='cancelada');
create policy "pasajeros propios" on pasajeros for select using (exists(select 1 from reservaciones r where r.id=reservacion_id and (r.usuario_id=auth.uid() or es_admin())));
create policy "pagos propios" on pagos for select using (exists(select 1 from reservaciones r where r.id=reservacion_id and (r.usuario_id=auth.uid() or es_admin())));
create policy "admin perfiles" on perfiles for all using (es_admin()) with check (es_admin());
create policy "admin destinos" on destinos for all using (es_admin()) with check (es_admin());
create policy "admin viajes" on viajes for all using (es_admin()) with check (es_admin());
create policy "admin reservas" on reservaciones for all using (es_admin()) with check (es_admin());
create policy "admin pasajeros" on pasajeros for all using (es_admin()) with check (es_admin());
create policy "admin pagos" on pagos for all using (es_admin()) with check (es_admin());
create policy "admin banners" on banners for all using (es_admin()) with check (es_admin());
create policy "admin configuración" on configuracion for all using (es_admin()) with check (es_admin());
create policy "configuración pública del sitio" on configuracion for select using (clave in ('redes_sociales','apariencia_sitio'));
create policy "crear solicitud de contacto" on solicitudes_contacto for insert with check (true);
create policy "admin solicitudes de contacto" on solicitudes_contacto for all using (es_admin()) with check (es_admin());

insert into public.configuracion(clave, valor)
values (
  'redes_sociales',
  '[{"id":"whatsapp","label":"WhatsApp","url":"","active":true,"order":1},{"id":"facebook","label":"Facebook","url":"","active":true,"order":2},{"id":"tiktok","label":"TikTok","url":"","active":true,"order":3},{"id":"instagram","label":"Instagram","url":"","active":true,"order":4},{"id":"email","label":"Correo electrónico","url":"mailto:admin@almare.com","active":true,"order":5}]'::jsonb
)
on conflict (clave) do nothing;

insert into public.configuracion(clave, valor)
values (
  'apariencia_sitio',
  '{"logoUrl":"","aboutTitle":"Quiénes somos","aboutText":"Somos una empresa acapulqueña creada para ayudarte a descubrir Acapulco, su cultura, sus paisajes y las experiencias que hacen único a nuestro puerto.","gradientStart":"#174f67","gradientEnd":"#4da693","gradientOpacity":82,"contactPrompt":"Nosotros te contactamos"}'::jsonb
)
on conflict (clave) do nothing;

insert into storage.buckets(id, name, public) values('destinos','destinos',true) on conflict(id) do update set public=true;
create policy "leer imágenes" on storage.objects for select using (bucket_id='destinos');
create policy "admin subir imágenes" on storage.objects for insert with check (bucket_id='destinos' and es_admin());
create policy "admin actualizar imágenes" on storage.objects for update using (bucket_id='destinos' and es_admin());
create policy "admin borrar imágenes" on storage.objects for delete using (bucket_id='destinos' and es_admin());

grant execute on function public.crear_reservacion(uuid,text,text,integer) to authenticated;
revoke update on public.perfiles from authenticated;
grant update(nombre, apellidos, telefono, fecha_nacimiento, sexo) on public.perfiles to authenticated;
grant update(estado) on public.reservaciones to authenticated;
